Repository ReCoded-Org/capstone-istanbul-no_barriers, pull requests merged in 2020-11, with the labels that each got.

#68 Feat: add Search bar in Resources page
  src/App.js
  src/components/AdvancedFilters/index.jsx
  src/components/NgoList/index.jsx
  src/components/PagesList/index.jsx
  src/components/SearchBar/__snapshots__/index.test.jsx.snap
  src/components/SearchBar/index.css
  src/components/SearchBar/index.jsx
  src/components/SearchBar/index.test.jsx
  src/containers/Resources/index.jsx
  src/locales/en.json
Labels: enhancement

#77 Feat: add Ngos list
  debug.log
  package.json
  public/index.html
  src/components/LocationPin/__snapshots__/index.test.jsx.snap
  src/components/LocationPin/index.css
  src/components/LocationPin/index.jsx
  src/components/LocationPin/index.test.jsx
  src/components/NgoDetails/__snapshots__/index.test.jsx.snap
  src/components/NgoDetails/index.css
  src/components/NgoDetails/index.jsx
  src/components/NgoDetails/index.test.jsx
  src/components/NgoDetailsDirection/__snapshots__/index.test.jsx.snap
  src/components/NgoDetailsDirection/index.css
  src/components/NgoDetailsDirection/index.jsx
  src/components/NgoDetailsDirection/index.test.jsx
  src/components/NgoList/__snapshots__/index.test.jsx.snap
  src/components/NgoList/allNgos.js
  src/components/NgoList/image/image.jpg
  src/components/NgoList/index.css
  src/components/NgoList/index.jsx
  src/components/NgoList/index.test.jsx
  src/components/NgoTableRow/__snapshots__/index.test.jsx.snap
  src/components/NgoTableRow/index.css
  src/components/NgoTableRow/index.jsx
  src/components/NgoTableRow/index.test.jsx
  src/components/PagesList/__snapshots__/index.test.jsx.snap
  src/components/PagesList/index.css
  src/components/PagesList/index.jsx
  src/components/PagesList/index.test.jsx
  src/locales/en.json
  yarn.lock
Labels: enhancement

#75 Stories
  src/App.js
  src/components/LoadingPage/index.css
  src/components/LoadingPage/index.jsx
  src/components/SingleStoryCard/index.css
  src/components/SingleStoryCard/index.jsx
  src/containers/Stories/index.jsx
  src/containers/Story/index.css
  src/containers/Story/index.jsx
  src/images/loading.gif
  src/locales/en.json
Labels: enhancement

#76 Feat: add Filters to the resources page
  src/components/AdvancedFilters/__snapshots__/index.test.jsx.snap
  src/components/AdvancedFilters/filters.js
  src/components/AdvancedFilters/functions.js
  src/components/AdvancedFilters/index.css
  src/components/AdvancedFilters/index.jsx
  src/components/AdvancedFilters/index.test.jsx
  src/components/FilterOptionsList/__snapshots__/index.test.jsx.snap
  src/components/FilterOptionsList/index.css
  src/components/FilterOptionsList/index.jsx
  src/components/FilterOptionsList/index.test.jsx
  src/components/SelectedFilterOptionList/__snapshots__/index.test.jsx.snap
  src/components/SelectedFilterOptionList/index.css
  src/components/SelectedFilterOptionList/index.jsx
  src/components/SelectedFilterOptionList/index.test.jsx
Labels: enhancement

#78 Functionality
  src/components/SearchBar/__snapshots__/index.test.jsx.snap
  src/components/SearchBar/index.jsx
  src/containers/Resources/index.jsx
  src/firebaseConfig.js
Labels: enhancement

#69 About us
  package.json
  src/App.js
  src/components/AboutUs/images/aboutus.png
  src/components/AboutUs/index.css
  src/components/AboutUs/index.jsx
  src/components/Footer/__snapshots__/index.test.jsx.snap
  src/components/Footer/index.jsx
  src/components/MeetTheTeam/images/ahmet.png
  src/components/MeetTheTeam/images/fadime.png
  src/components/MeetTheTeam/images/halit.png
  src/components/MeetTheTeam/images/khaldoon.png
  src/components/MeetTheTeam/images/zeynep.png
  src/components/MeetTheTeam/index.css
  src/components/MeetTheTeam/index.jsx
  src/components/MeetTheTeam/team.js
  src/components/NavBar/index.jsx
  src/components/TeamMember/__snapshots__/index.test.jsx.snap
  src/components/TeamMember/index.jsx
  src/components/TeamMember/index.test.jsx
  src/index.js
  src/locales/ar.json
  src/locales/en.json
  yarn.lock
Labels: enhancement

#87 Signup Page complete.
  src/App.js
  src/components/NavBar/__snapshots__/index.test.jsx.snap
  src/components/NavBar/index.jsx
  src/components/SignUp/__snapshots__/index.test.jsx.snap
  src/components/SignUp/index.css
  src/components/SignUp/index.jsx
  src/components/SignUp/index.test.jsx
  src/firebaseConfig.js
  src/locales/en.json
  src/redux/action/index.jsx
  src/redux/action/types.js
  src/redux/reducers/index.jsx
Labels: enhancement

#82 Feat add Profile Page without main functionality
  src/App.js
  src/components/EditProfile/__snapshots__/index.test.jsx.snap
  src/components/EditProfile/index.jsx
  src/components/EditProfile/index.test.jsx
  src/components/PersonalBlogPosts/__snapshots__/index.test.jsx.snap
  src/components/PersonalBlogPosts/index.css
  src/components/PersonalBlogPosts/index.jsx
  src/components/PersonalBlogPosts/index.test.jsx
  src/components/PersonalBlogPosts/profile.jpg
  src/components/PersonalInformation/__snapshots__/index.test.jsx.snap
  src/components/PersonalInformation/index.css
  src/components/PersonalInformation/index.jsx
  src/components/PersonalInformation/index.test.jsx
  src/components/PersonalInformation/profile.jpg
  src/components/RenderBlogPost/__snapshots__/index.test.jsx.snap
  src/components/RenderBlogPost/index.css
  src/components/RenderBlogPost/index.jsx
  src/components/RenderBlogPost/index.test.jsx
  src/components/RenderBlogPost/profile.jpg
  src/containers/Profile/index.css
  src/containers/Profile/index.jsx
  src/locales/en.json
Labels: enhancement

#86 Find now
  package.json
  src/App.js
  src/components/BrowseCategory/index.css
  src/components/BrowseCategory/index.jsx
  src/components/ExploreBlogs/__snapshots__/index.test.jsx.snap
  src/components/ExploreBlogs/index.css
  src/components/ExploreBlogs/index.jsx
  src/components/Footer/__snapshots__/index.test.jsx.snap
  src/components/Footer/index.css
  src/components/Footer/index.jsx
  src/components/GetStarted/__snapshots__/index.test.jsx.snap
  src/components/GetStarted/index.css
  src/components/GetStarted/index.jsx
  src/components/Header/__snapshots__/index.test.jsx.snap
  src/components/Header/index.css
  src/components/Header/index.jsx
  src/components/Header/index.test.jsx
  src/components/HowDoesItWork/index.css
  src/components/NavBar/__snapshots__/index.test.jsx.snap
  src/components/NavBar/index.jsx
  src/components/SelectedFilterOptionList/index.test.jsx
  src/components/SignUp/__snapshots__/index.test.jsx.snap
  src/components/SignUp/index.jsx
  src/components/TrustedBy/index.css
  src/containers/Resources/index.jsx
  src/locales/en.json
  src/redux/action/index.jsx
  src/redux/action/types.js
  src/redux/reducers/index.jsx
  src/redux/store/store.js
  yarn.lock
Labels: enhancement

#91 Explore Blog Bug Fix
  src/components/ExploreBlogs/__snapshots__/index.test.jsx.snap
  src/components/ExploreBlogs/index.css
  src/components/ExploreBlogs/index.jsx
  src/components/ExploreBlogs/index.test.jsx
Labels: Fix Bug

#89 fix styling and responsive
  src/App.js
  src/components/Features/__snapshots__/index.test.jsx.snap
  src/components/NavBar/__snapshots__/index.test.jsx.snap
  src/components/NavBar/index.jsx
  src/components/SignIn/__snapshots__/index.test.jsx.snap
  src/components/SignIn/index.css
  src/components/SignIn/index.jsx
  src/components/SignIn/index.test.jsx
  src/components/SingleFeature/index.css
  src/components/SingleFeature/index.jsx
Labels: Fix Bug

#90 Find ngos
  src/components/AdvancedFilters/__snapshots__/index.test.jsx.snap
  src/components/AdvancedFilters/filters.js
  src/components/AdvancedFilters/functions.js
  src/components/AdvancedFilters/index.css
  src/components/AdvancedFilters/index.jsx
  src/components/AdvancedFilters/index.test.jsx
  src/components/FilterOptionsList/__snapshots__/index.test.jsx.snap
  src/components/FilterOptionsList/index.jsx
  src/components/FilterOptionsList/index.test.jsx
  src/components/NavBar/__snapshots__/index.test.jsx.snap
  src/components/NavBar/index.jsx
  src/components/NgoDetails/__snapshots__/index.test.jsx.snap
  src/components/NgoDetails/index.jsx
  src/components/NgoList/__snapshots__/index.test.jsx.snap
  src/components/NgoList/allNgos.js
  src/components/NgoList/index.jsx
  src/components/NgoList/index.test.jsx
  src/components/NgoTableRow/__snapshots__/index.test.jsx.snap
  src/components/NgoTableRow/index.jsx
  src/components/NgoTableRow/index.test.jsx
  src/components/PagesList/index.jsx
  src/components/PagesList/index.test.jsx
  src/components/SearchBar/index.css
  src/components/SelectedFilterOptionList/__snapshots__/index.test.jsx.snap
  src/components/SelectedFilterOptionList/index.jsx
  src/components/SelectedFilterOptionList/index.test.jsx
  src/containers/Resources/index.jsx
  src/locales/en.json
Labels: enhancement

#93 add blogs functionality in profile
  src/components/PersonalBlogPosts/__snapshots__/index.test.jsx.snap
  src/components/PersonalBlogPosts/index.css
  src/components/PersonalBlogPosts/index.jsx
  src/components/PersonalBlogPosts/index.test.jsx
  src/components/PersonalBlogPosts/profile.jpg
  src/components/PersonalInformation/__snapshots__/index.test.jsx.snap
  src/components/PersonalInformation/index.jsx
  src/components/RenderBlogPost/__snapshots__/index.test.jsx.snap
  src/components/RenderBlogPost/index.css
  src/components/RenderBlogPost/index.jsx
  src/components/RenderBlogPost/index.test.jsx
  src/components/RenderBlogPost/profile.jpg
  src/containers/Profile/index.jsx
Labels: enhancement

#96 Feat: add func and onClick for different languages
  src/components/NavBar/__snapshots__/index.test.jsx.snap
  src/components/NavBar/index.jsx
Labels: enhancement

#99 Fix NavBar
  src/components/NavBar/__snapshots__/index.test.jsx.snap
  src/components/NavBar/index.css
  src/components/NavBar/index.jsx
Labels: Fix Bug

#104 add arabic Translation
  src/locales/ar.json
Labels: enhancement

#102 Fix Fetch stories based on translation
  src/containers/Stories/index.jsx
Labels: enhancement

#106 Fix home blogs
  src/components/ExploreBlogs/index.jsx
Labels: enhancement

#107 Add Translation To Features Component
  src/components/Features/__snapshots__/index.test.jsx.snap
  src/components/Features/contents.jsx
  src/components/Features/index.jsx
  src/locales/en.json
Labels: Fix Bug

#108 Add Translation to Get started
  src/components/GetStarted/__snapshots__/index.test.jsx.snap
  src/components/GetStarted/index.jsx
  src/locales/en.json
Labels: Fix Bug

#114 Feat: add TR translation to json file
  src/locales/tr.json
Labels: documentation

#109 Add translation to HowDoesItWork
  src/components/HowDoesItWork/__snapshots__/index.test.jsx.snap
  src/components/HowDoesItWork/index.jsx
  src/components/TrustedBy/__snapshots__/index.test.jsx.snap
  src/components/TrustedBy/index.jsx
  src/locales/en.json
Labels: Fix Bug

#111 Resources fixes
  src/components/AdvancedFilters/__snapshots__/index.test.jsx.snap
  src/components/AdvancedFilters/index.css
  src/components/AdvancedFilters/index.jsx
  src/components/Features/__snapshots__/index.test.jsx.snap
  src/components/FilterOptionsList/index.css
  src/components/FilterOptionsList/index.jsx
  src/components/Footer/__snapshots__/index.test.jsx.snap
  src/components/Footer/index.jsx
  src/components/Header/index.css
  src/components/NavBar/index.jsx
  src/components/NavBar/index.test.jsx
  src/components/NgoDetails/__snapshots__/index.test.jsx.snap
  src/components/NgoDetails/index.jsx
  src/components/NgoDetails/index.test.jsx
  src/components/NgoList/__snapshots__/index.test.jsx.snap
  src/components/NgoList/index.jsx
  src/components/NgoTableRow/index.jsx
  src/components/SelectedFilterOptionList/__snapshots__/index.test.jsx.snap
  src/components/SelectedFilterOptionList/index.css
  src/components/SelectedFilterOptionList/index.jsx
  src/components/SingleCategory/index.css
  src/components/SingleFeature/index.jsx
  src/containers/Resources/index.css
  src/containers/Resources/index.jsx
  src/redux/action/index.jsx
  src/redux/action/types.js
  src/redux/reducers/index.jsx
Labels: Fix Bug, enhancement

#117 Fix sign out
  src/components/NavBar/__snapshots__/index.test.jsx.snap
  src/components/NavBar/index.jsx
  src/components/NavBar/index.test.jsx
  src/locales/en.json
Labels: Fix Bug, enhancement

#119 Complete Arabic translation.
  src/locales/ar.json
Labels: enhancement

#120 fix bugs
  src/components/ExploreBlogs/index.jsx
  src/components/NavBar/index.jsx
  src/components/NavBar/index.test.jsx
  src/locales/ar.json
Labels: Fix Bug, enhancement
